In [1]:
# Importing Required Libraries
import pandas as pd
import os

In [2]:
# Function to check and convert date format
def convert_date_format(date_series):
    try:
        # Attempt to convert to datetime with format %d/%m/%Y
        converted_dates = pd.to_datetime(date_series, format='%d/%m/%Y')
        return converted_dates.dt.strftime('%Y/%m/%d')
    except ValueError:
        # If conversion fails, return the original series
        return date_series

In [9]:
# Data path
file_path = r'C:\Users\mh30f\OneDrive\Documents\GitHub\YDOC2MySQL\Resources'

# Iterate over all CSV files in the specified directory
all_dataframes = []

for filename in os.listdir(file_path):
    if filename.endswith('.csv'):
        file_path_full = os.path.join(file_path, filename)

        # Read CSV and convert to db_name
        db_name = pd.read_csv(file_path_full)

        # Drop rows 2 and 3 (index 1 and 2 since indexing starts at 0)
        db_name = db_name.drop([0, 1]).reset_index(drop=True)

        # Ensure 'Date' column is in the correct format 'YYYY/MM/DD'
        db_name['Date'] = convert_date_format(db_name['Date'])

        # Merge 'Date' and 'Time' columns into a new column 'DateTime'
        db_name['DateTime'] = pd.to_datetime(db_name['Date'] + ' ' + db_name['Time'], format='%Y/%m/%d %H:%M:%S')

        # Drop the original 'Date' and 'Time' columns if no longer needed
        db_name = db_name.drop(columns=['Date', 'Time'])

        # Drop rows with any NaN values (if needed)
        db_name = db_name.dropna()

        # Reorder columns to move 'DateTime' to the first position
        db_name = db_name[['DateTime'] + [col for col in db_name.columns if col != 'DateTime']]

        # Store the processed DataFrame in the list
        all_dataframes.append(db_name)

# Optionally, concatenate all DataFrames into a single DataFrame if needed
all_data = pd.concat(all_dataframes, ignore_index=True)

# Show the final DataFrame
all_data

,DateTime,Water Level,Temp,Barometric pressure,Compensated Pressure,Casing temperature,Min voltage,EXT POWER / SOLAR,P01,P02,...,P06,P07,P08,P09,P10,P11,P12,P13,P14,P15
0,2024-09-25 00:15:00,13.599,31414.99,31395.36,28.673,3.318,10.281,20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-09-25 00:30:00,13.6,30987.75,30964.87,28.906,3.321,10.279,20,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-25 00:45:00,13.6,30351.1,30328.69,28.906,3.322,10.279,19.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-25 01:00:00,13.6,30819.11,30796.35,28.906,3.323,10.277,19.8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-09-25 01:15:00,13.599,30680.76,30661.59,28.673,3.323,10.277,19.6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-09-25 01:30:00,13.597,29951.23,29932.45,28.677,3.323,10.274,19.5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-09-25 01:45:00,13.598,31210.2,31187.02,28.914,3.323,10.275,19.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-09-25 02:00:00,13.595,30516.17,30497.11,28.673,3.321,10.273,19.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2024-09-25 02:15:00,13.595,30459.93,30437.44,28.906,3.32,10.275,19.1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-09-25 02:30:00,13.598,29278.85,29257.23,28.906,3.322,10.276,19,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2024-09-25 02:45:00,13.597,29582.7,29564.03,28.686,3.322,10.275,18.9,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2024-09-25 03:00:00,13.595,29947.25,29925.06,28.91,3.321,10.274,18.8,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2024-09-25 00:15:00,14.844,17.15,10.399,4.445,11.4,3.16,0.207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2024-09-25 00:30:00,14.844,17.15,10.395,4.449,11.4,3.3,0.203,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2024-09-25 00:45:00,14.844,17.15,10.396,4.448,11.4,3.3,0.199,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2024-09-25 01:00:00,14.844,17.15,10.395,4.449,11.3,3.3,0.197,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2024-09-25 01:15:00,14.844,17.15,10.395,4.449,11.2,3.31,0.199,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2024-09-25 01:30:00,14.841,17.15,10.394,4.447,11.1,3.3,0.201,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2024-09-25 01:45:00,14.841,17.15,10.394,4.447,11.1,3.3,0.198,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2024-09-25 02:00:00,14.841,17.15,10.392,4.449,11,3.3,0.204,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2024-09-25 02:15:00,14.841,17.15,10.395,4.446,10.9,3.3,0.193,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2024-09-25 02:30:00,14.838,17.15,10.393,4.445,10.9,3.3,0.199,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2024-09-25 02:45:00,14.838,17.15,10.394,4.444,10.8,3.3,0.198,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2024-09-25 03:00:00,14.841,17.15,10.394,4.447,10.8,3.3,0.194,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2024-09-25 03:15:00,14.841,17.15,10.397,4.444,10.7,3.3,0.193,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2024-09-25 03:30:00,14.838,17.15,10.394,4.444,10.7,3.3,0.198,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2024-09-25 03:45:00,14.838,17.15,10.397,4.441,10.6,3.3,0.198,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2024-09-25 04:00:00,14.838,17.15,10.394,4.444,10.4,3.3,0.203,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2024-09-25 04:15:00,14.838,17.15,10.392,4.446,10.3,3.3,0.199,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2024-09-25 04:30:00,14.841,17.15,10.397,4.444,10.2,3.3,0.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2024-09-25 04:45:00,14.838,17.15,10.397,4.441,10,3.3,0.196,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2024-09-25 05:00:00,14.838,17.15,10.397,4.441,9.7,3.3,0.196,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2024-09-25 05:15:00,14.841,17.15,10.397,4.444,9.4,3.3,0.201,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2024-09-25 05:30:00,14.841,17.15,10.401,4.44,9,3.3,0.201,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2024-09-25 05:45:00,14.844,17.15,10.4,4.444,8.6,3.3,0.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2024-09-25 06:00:00,14.844,17.15,10.402,4.442,8.2,3.26,0.197,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN